# Abstract

In my term project, I plan to analyze the effects of ridesharing services on public transit system use within the United States. Specifically, I will analyze whether increased ridesharing is related to increases, decreases, or no changes in public transit ridership. While people commonly hypothesize that ridesharing reduces public transit use, very few studies have been conducted on that specific topic. Past studies suggest that few people frequently use ridesharing services, though there are many other users who rideshare infrequently. Ridesharing tends to favor those in younger and wealthier demographics compared to most other modes such as public transit, biking, and taxis. Studies are available that compare transit or ridesharing use to specific demographic variables such as race or age, but they do not compare them together. Data from the 2009 and 2017 National Household Travel Surveys will be used for my analysis. Since ridesharing was not a sufficiently common mode of transportation in 2009, ridesharing data was not collected and the data may need to be treated as though there was no ridesharing in 2009. Other information analyzed to compare to transit and rideshare use will likely include rider demographics such as age or family income. 

