# Data

The data for this study comes from the 2009 and 2017 National Household Travel Surveys (NHTS). The NHTS collects detailed data on travel behavior within the United States by surveying selected regions and adjusting the data to represent trends in the country as a whole. The data can be classified as being collected to describe households, persons, workers, vehicles, and trips. Some data categories are added and removed from between different iterations of the NHTS, but most categories remain consistent.

The data collected for households includes the number of people, drivers, workers, and vehicles, the income, the housing type, whether the residence is owned or rented, the race and hispanic status of the household reference person, the tract and block group characteristics, and internet use and delivery. The 2009 NHTS also includes information about the number of cell phones and other phones in the household, but the 2017 NHTS does not.

The data collected on persons includes the age, sex, relationship to the reference person, driver status, worker status or primary occupation, internet use, home deliveries from internet shopping, travel disability, effects of disability on mobility, education level, immigrant status, views on transportation, annual number of miles driven, public transit and motorcycle in the last month, and biking and walking trips in the last week. The 2009 NHTS includes school trips for children and individual internet use, while the 2017 NHTS adds the number of biking and walking trips for exercise, rideshare app use and rideshare service from the last month, usual mode of travel for getting to school, and the use of the travel log on the days trips were taken.

All data collected for workers used the same categories in 2009 and 2017- whether the job was full-time or part-time, if the person worked more than one job, the category of the occupation, the workplace location, the typical mode used to travel to work, whether workers drove alone or carpooled, the typical distance traveled to get to work, the typical travel time to work, whether the person works from home, usual arrivel time at work, and flexibility in time of arrival at work.

The vehicle data includes car make, model, and age, the amount of miles driven annually, how long the vehicle has been owned, the vehicle odometer reading, whether the vehicle uses alternative fuel, and who the primary driver is. The 2009 NHTS states whether the vehicle is commercially owned, and the 2017 NHTS lists vehicle body type, fuel type, and hybrid type for hybrid vehicles.

Trip data includes origin and destination addresses, tip start and end times,trip distance, trip purpose, travel party size, the last time of travel, and the means of transportation including vehicle type, which household vehicle is used, wait time for transit, and access and egress mode for transit. The 2009 NHTS includes additional data for interstate use and toll payment.

Important categories within the given data include rideshare app use, actual rideshare service use, transit use, and means of travel. Other data may be used to provide clarity to trends shown within the data.